// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFront() {
  return window['go']['main']['App']['BringToFront']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function HandleWindowClose() {
  return window['go']['main']['App']['HandleWindowClose']();
}

export function InitTray() {
  return window['go']['main']['App']['InitTray']();
}

export function IsVisible() {
  return window['go']['main']['App']['IsVisible']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function SendToDiscord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToDiscord'](arg1, arg2, arg3);
}

export function SetWebhookURL(arg1) {
  return window['go']['main']['App']['SetWebhookURL'](arg1);
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ToggleVisibility() {
  return window['go']['main']['App']['ToggleVisibility']();
}
