// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BringToFront() {
  return window['go']['main']['App']['BringToFront']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDataPath() {
  return window['go']['main']['App']['GetDataPath']();
}

export function GetFileSize(arg1) {
  return window['go']['main']['App']['GetFileSize'](arg1);
}

export function GetStatistics() {
  return window['go']['main']['App']['GetStatistics']();
}

export function GetStorageInfo() {
  return window['go']['main']['App']['GetStorageInfo']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function HandleWindowClose() {
  return window['go']['main']['App']['HandleWindowClose']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function InitTray() {
  return window['go']['main']['App']['InitTray']();
}

export function IsInWindowsStartup() {
  return window['go']['main']['App']['IsInWindowsStartup']();
}

export function IsVisible() {
  return window['go']['main']['App']['IsVisible']();
}

export function Maximize() {
  return window['go']['main']['App']['Maximize']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenUpdateURL(arg1) {
  return window['go']['main']['App']['OpenUpdateURL'](arg1);
}

export function ResetSessionStats() {
  return window['go']['main']['App']['ResetSessionStats']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendToDiscord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToDiscord'](arg1, arg2, arg3);
}

export function SetWebhookURL(arg1) {
  return window['go']['main']['App']['SetWebhookURL'](arg1);
}

export function SetWindowsStartup(arg1) {
  return window['go']['main']['App']['SetWindowsStartup'](arg1);
}

export function ShowCustomTrayMenu() {
  return window['go']['main']['App']['ShowCustomTrayMenu']();
}

export function ShowFromTray() {
  return window['go']['main']['App']['ShowFromTray']();
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function StartMonitoring() {
  return window['go']['main']['App']['StartMonitoring']();
}

export function StopMonitoring() {
  return window['go']['main']['App']['StopMonitoring']();
}

export function ToggleVisibility() {
  return window['go']['main']['App']['ToggleVisibility']();
}

export function UpdateMonitorPath(arg1) {
  return window['go']['main']['App']['UpdateMonitorPath'](arg1);
}
