// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {version} from '../models';
import {main} from '../models';

export function BringToFront():Promise<void>;

export function CheckForUpdates():Promise<version.UpdateInfo>;

export function CreateDesktopShortcut():Promise<void>;

export function ExportData(arg1:string):Promise<void>;

export function GetAppStatus():Promise<main.AppStatus>;

export function GetBuildInfo():Promise<version.BuildInfo>;

export function GetConfig():Promise<main.Config>;

export function GetDataPath():Promise<string>;

export function GetFileSize(arg1:string):Promise<number>;

export function GetMedalTVClipFolder():Promise<string>;

export function GetMedalTVClips():Promise<Array<main.ClipDisplayData>>;

export function GetMonitoredPaths():Promise<Array<string>>;

export function GetNVIDIACurrentDirectory():Promise<string>;

export function GetStatistics():Promise<main.Stats>;

export function GetStorageInfo():Promise<Record<string, any>>;

export function GetUptime():Promise<string>;

export function GetVersion():Promise<string>;

export function GetVersionInfo():Promise<Record<string, string>>;

export function HandleWindowClose():Promise<void>;

export function HasDesktopShortcut():Promise<boolean>;

export function ImportData(arg1:string):Promise<void>;

export function InitTray():Promise<void>;

export function IsInWindowsStartup():Promise<boolean>;

export function IsVisible():Promise<boolean>;

export function Maximize():Promise<void>;

export function Minimize():Promise<void>;

export function MinimizeToTray():Promise<void>;

export function OpenUpdateURL(arg1:string):Promise<void>;

export function RemoveDesktopShortcut():Promise<void>;

export function ResetSessionStats():Promise<void>;

export function RestartMonitoring():Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SelectFolder():Promise<string>;

export function SendClipToDiscord(arg1:string):Promise<void>;

export function SendToDiscord(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetDesktopShortcut(arg1:boolean):Promise<void>;

export function SetWebhookURL(arg1:string):Promise<void>;

export function SetWindowsStartup(arg1:boolean):Promise<void>;

export function ShowCustomTrayMenu():Promise<void>;

export function ShowFromTray():Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function StartMonitoring():Promise<void>;

export function StopMonitoring():Promise<void>;

export function ToggleVisibility():Promise<void>;

export function UpdateMonitorPath(arg1:string):Promise<void>;
