// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1, arg2) {
  return window['go']['main']['NotificationHandler']['Notify'](arg1, arg2);
}

export function SendSystemNotification(arg1, arg2) {
  return window['go']['main']['NotificationHandler']['SendSystemNotification'](arg1, arg2);
}

export function SendVideoNotification(arg1, arg2) {
  return window['go']['main']['NotificationHandler']['SendVideoNotification'](arg1, arg2);
}

export function SendVideoSystemNotification(arg1, arg2) {
  return window['go']['main']['NotificationHandler']['SendVideoSystemNotification'](arg1, arg2);
}

export function TestNotification() {
  return window['go']['main']['NotificationHandler']['TestNotification']();
}
